version: '3.8'

services:
  sheapgamer-bot:
    build: .
    container_name: sheapgamer-discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - RSS_FEED_URL=https://rss.app/feeds/COiTZRnT26oDqrJf.xml
      - RSS_DELAY=${RSS_DELAY}
    restart: unless-stopped
    env_file:
      - stack.env
